project_name: "Project Lumina"
mlflow_experiment_name: "Lumina-Fraud-Detection"
model_registry_name: "Lumina-Fraud-GNN"

data:
  raw_dir: "data"
  processed_path: "data/processed/graph_data.pt"

model:
  name: "GCN"
  params:
    hidden_channels: 128
    out_channels: 2 # Licit vs Illicit

training:
  lr: 0.01
  epochs: 50
  test_split_ratio: 0.3
  val_split_ratio: 0.5 # 50% of the test set as validation set
